"""baseline

Revision ID: 0339113e0bab
Revises: 
Create Date: 2026-08-28 14:04:48.481445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0339113e0bab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('is_importer', sa.Boolean(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_id'), 'manufacturers', ['id'], unique=False)
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=False)
    op.create_index(op.f('ix_manufacturers_registration_number'), 'manufacturers', ['registration_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ecommerce_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('has_country_of_origin_filter', sa.Boolean(), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.Column('evidence_image_path', sa.String(), nullable=True),
    sa.Column('checked_by_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecommerce_checks_check_id'), 'ecommerce_checks', ['check_id'], unique=True)
    op.create_index(op.f('ix_ecommerce_checks_id'), 'ecommerce_checks', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('last_compliance_score', sa.Float(), nullable=True),
    sa.Column('last_scan_id', sa.String(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_manufacturer', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legal_reference', sa.String(), nullable=True),
    sa.Column('category_scope', sa.JSON(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_conduct_bucket', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('retired_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['retired_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_code'), 'rules', ['code'], unique=True)
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('relaxation_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gazette_reference', sa.String(), nullable=True),
    sa.Column('applies_to_categories', sa.JSON(), nullable=True),
    sa.Column('applies_to_states', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relaxation_orders_id'), 'relaxation_orders', ['id'], unique=False)
    op.create_index(op.f('ix_relaxation_orders_order_number'), 'relaxation_orders', ['order_number'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_language', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('pipeline_status', sa.String(), nullable=True),
    sa.Column('calibration_method', sa.String(), nullable=True),
    sa.Column('calibration_data', sa.JSON(), nullable=True),
    sa.Column('symbols_detected', sa.JSON(), nullable=True),
    sa.Column('barcode_data', sa.JSON(), nullable=True),
    sa.Column('groq_used', sa.Boolean(), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('field_results', sa.JSON(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=True)
    op.create_table('manual_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_code', sa.String(), nullable=True),
    sa.Column('finding_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_findings_id'), 'manual_findings', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash_sha256', sa.String(), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_report_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_manual_findings_id'), table_name='manual_findings')
    op.drop_table('manual_findings')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_relaxation_orders_order_number'), table_name='relaxation_orders')
    op.drop_index(op.f('ix_relaxation_orders_id'), table_name='relaxation_orders')
    op.drop_table('relaxation_orders')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_code'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ecommerce_checks_id'), table_name='ecommerce_checks')
    op.drop_index(op.f('ix_ecommerce_checks_check_id'), table_name='ecommerce_checks')
    op.drop_table('ecommerce_checks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_manufacturers_registration_number'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_id'), table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
