"""add compliance checks

Revision ID: ac732dc0c569
Revises: 0339113e0bab
Create Date: 2026-08-28 14:55:08.950981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac732dc0c569'
down_revision: Union[str, None] = '0339113e0bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('result', sa.Enum('Pass', 'Fail', 'NotApplicable', 'Relaxed', 'ManualReviewRequired', name='compliancecheckresult'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_value', sa.String(), nullable=True),
    sa.Column('relaxation_order_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relaxation_order_id'], ['relaxation_orders.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_field_key'), 'compliance_checks', ['field_key'], unique=False)
    op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_scan_id'), 'compliance_checks', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_checks_scan_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_field_key'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    # ### end Alembic commands ###
