import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Legacy gov.* tokens kept for backward-compat with any un-migrated markup.
        gov: {
          navy: "#003580",
          dark: "#00224f",
          light: "#d6e4ff",
          saffron: "#FF6B00",
        },
        // LegalM Stitch design-system tokens (see legalm_design_system/DESIGN.md)
        "on-error-container": "#93000a",
        "secondary-fixed": "#d7e2ff",
        "outline-variant": "#c4c6cf",
        surface: "#f8f9ff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed": "#6ffbbe",
        "on-surface-variant": "#44474e",
        "secondary-container": "#659dfe",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        background: "#f8f9ff",
        tertiary: "#000d06",
        "on-secondary-fixed-variant": "#004491",
        "on-primary-fixed": "#001b3d",
        "on-tertiary-container": "#009c6b",
        secondary: "#115cb9",
        "on-secondary-container": "#003370",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed-variant": "#2d476f",
        "primary-fixed": "#d6e3ff",
        "status-fail": "#ef4444",
        "border-subtle": "#e2e8f0",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        "surface-tint": "#465f88",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#aec7f6",
        "tertiary-fixed-dim": "#4edea3",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#001a40",
        "surface-container-high": "#dce9ff",
        "inverse-primary": "#aec7f6",
        "on-primary-container": "#708ab5",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d3e4fe",
        error: "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#acc7ff",
        primary: "#000a1e",
        outline: "#74777f",
        "status-pass": "#10b981",
        "tertiary-container": "#002718",
        "bg-offset": "#f8fafc",
        "primary-container": "#002147",
        "on-background": "#0b1c30",
        "on-secondary": "#ffffff",
        "status-review": "#f59e0b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
        unit: "4px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "700", letterSpacing: "0.06em" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
